discord_token: "ODM2NjkzNzYxNjkwMDQyNDA4.YIhtyQ.QlTguqpvUEntyJD0LaQieeQdKvI"
client_id: "38754712208-kv8cg40gbksnpj4kcd5fiog2bck9n20j.apps.googleusercontent.com"
client_secret: "blnZg208ta2KrRgSA3NugBCx"
redirect_uri: "http://localhost:8080/auth"
